version: "3.9"

services:

  postgres:
    image: postgres:14.2
    environment:
      POSTGRES_USER: jurus
      POSTGRES_PASSWORD: test_db_password
    ports: 
      - '5432:5432'
    volumes:
      - /var/lib/postgresql/data
    networks:
      - elk

  redis:
    image: redis:7.0
    ports:
      - '6379:6379'
    networks:
      - elk

  jurus:
    build:
      context: .
    volumes:
      - ./jurus:/opt/app
    links:
      - postgres
      - redis
    ports:
      - '8010:8010'
    env_file:
      - .env
    networks:
      - elk

  sidekiq:
    build:
      context: .
    command: bundle exec sidekiq 
    links:
      - postgres
      - redis
    env_file:
      - .env
    networks:
      - elk


  elasticsearch:
    build:
      context: elasticsearch/
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - elasticsearch:/usr/share/elasticsearch/data/:rw
    ports:
      - "127.0.0.1:9200:9200"
      - "127.0.0.1:9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx1g -Xms1g"
    networks:
      - elk

  logstash:
    build:
      context: logstash/
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
      - /home/proxy_logs:/home/proxy_logs:ro
    ports:
      - "1025:1025/udp"
      - "127.0.0.1:5000:5000"
      - "127.0.0.1:9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx1g -Xms1g"
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    build:
      context: kibana/
    volumes:
      - ./kibana/config/:/usr/share/kibana/config:ro
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

  nginx:
    build:
      context: .
      dockerfile: ./Dockerfile.nginx
    depends_on:
      - kibana
    ports:
      - '8020:8020'
      - '8030:8030'
      - '80:80'
    networks:
      - elk

volumes:
  elasticsearch:
    driver: local
  
networks:
  elk:
    driver: bridge
